<a href="https://colab.research.google.com/github/Okega/Projects_For_Linear_Algebra/blob/master/Practice_with_Gram_Schmidt_Process.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# import the numpy library....

import matplotlib.pyplot as plt
from sympy import Poly
import sympy as sym
import numpy as np
from numpy import c_

# We'll specify that x and t are variables:
x, t = sym.symbols('x, t')

ll = "loaded"

In [ ]:
#  How do I do a dot product?
np.dot([ 1, 2], [ 3, 4])

# How do I find the magnitude in np?
np.sqrt(np.dot([1,2],[1,2]))

11

In [2]:
#  Define the original vectors:

r1 = [ 0, 3, -3, 0 ]
r2 = [ 2, 6, -2, 2]
r3 = [ -2, 1, -3, 0]
r4 = [ 2, -4, -2, -4]

# Look at r1:
r1


[0, 3, -3, 0]

In [3]:
#  Find the first nice basis vector u1:

# 1:  Pick a new vector
r1

# 2:  Subtract the projection of r1 onto the nice basis  u1, u2, u3...
#     and save this as a temp vector n1
n1 = r1
n1

# 3:  Find the magnitude of n1
np.sqrt(np.dot(n1, n1))

# 4:  Create the nice basis vector u1 = 1/ | n1 |  * n1
u1 = n1 / np.sqrt(np.dot(n1,n1))
u1


array([ 0.        ,  0.70710678, -0.70710678,  0.        ])

In [4]:
# Check that u1 has magnitude 1:
np.dot(u1, u1)

1.0000000000000002

In [5]:
#  Find the second nice basis vector u2:

# 1:  Pick a new vector
r2

# 2:  Subtract the projection of r2 onto the nice basis  u1, u2, u3...
#     and save this as a temp vector n2
n2 = r2 - np.dot(r2, u1) * u1
n2

# 3:  Find the magnitude of n2
np.sqrt(np.dot(n2, n2))

# 4:  Create the nice basis vector u2 = 1/ | n2 |  * n2
u2 = n2 / np.sqrt(np.dot(n2,n2))
u2

array([0.5, 0.5, 0.5, 0.5])

In [7]:
#  Check that u1 and u2 are orthogonal:
np.dot(u1, u2)

# Check that u2 has magnitude 1:
np.dot(u2, u2)

1.0

In [8]:
# Find the third nice basis vector u3:

# 1:  Pick a new vector
r3

# 2:  Subtract the projection of r3 onto the nice basis  u1, u2, ...
#     and save this as a temp vector n3
n3 = r3 - np.dot(r3, u1) * u1 - np.dot(r3, u2) * u2
n3

# 3:  Find the magnitude of n2
np.sqrt(np.dot(n3, n3))

# 4:  Create the nice basis vector u3 = 1/ | n3 |  * n3
u3 = n3 / np.sqrt(np.dot(n3,n3))
u3

array([-7.07106781e-01, -3.14018492e-16,  9.42055475e-16,  7.07106781e-01])

In [9]:
#  Check that u3 is orthogonal to u1 and u2
print(np.dot(u1, u3))
print(np.dot(u2, u3))
print(np.dot(u3,u3))

-8.881784197001252e-16
6.106226635438361e-16
0.9999999999999998


In [10]:
# Find the third nice basis vector u4:

# 1:  Pick a new vector
r4

# 2:  Subtract the projection of r4 onto the nice basis  u1, u2, u3 ...
#     and save this as a temp vector n4
n4 = r4 - np.dot(r4, u1) * u1 - np.dot(r4, u2) * u2 - np.dot(r4, u3) * u3
n4

# 3:  Find the magnitude of n4
np.sqrt(np.dot(n4, n4))

# 4:  Create the nice basis vector u4 = 1/ | n4 |  * n4
u4 = n4 / np.sqrt(np.dot(n4,n4))
u4

array([ 0.5, -0.5, -0.5,  0.5])

In [11]:
# Check that u4 is orthogonal to u1, u2, and u3
# and check that |u4| = 1
print(np.dot(u4, u1))
print(np.dot(u4, u2))
print(np.dot(u4, u3))
print(np.dot(u4, u4))


-2.4424906541753444e-15
1.1657341758564144e-15
5.551115123125783e-17
0.9999999999999999
